services:
  axon-server:
    container_name: axon_server
    image: axoniq/axonserver:latest-jdk-17
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - cqrs
  command_postgres:
    container_name: command_postgres
    image: postgres:17.2
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - cqrs
  query_postgres:
    container_name: query_postgres
    image: postgres:17.2
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    networks:
      - cqrs
networks:
  cqrs: