spring:
  application:
    name: command-service
  datasource:
    url: jdbc:postgresql://localhost:5432/commandsdb
    username: user1
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
#axoniq:
#  console:
#    application-name: axon-cqrs
#    credentials:
#    dlq-mode: FULL
